import {
  Building2,
  Eye,
  Baby,
  Stethoscope,
  Bone,
  Smile,
  Ear,
  Heart,
  Brain,
  Activity,
  Thermometer,
  Calendar,
  FlaskConical,
  Pill,
  Truck,
  Droplets,
} from 'lucide-react';

export const blobColors = [
  { bg: '#E8F5E9', icon: '#2E7D32' },
  { bg: '#E3F2FD', icon: '#1565C0' },
  { bg: '#FFF3E0', icon: '#E65100' },
  { bg: '#FCE4EC', icon: '#C62828' },
  { bg: '#F3E5F5', icon: '#6A1B9A' },
  { bg: '#E0F7FA', icon: '#00695C' },
  { bg: '#FFF8E1', icon: '#F57F17' },
  { bg: '#E8EAF6', icon: '#283593' },
  { bg: '#FFEBEE', icon: '#B71C1C' },
  { bg: '#E0F2F1', icon: '#004D40' },
];

export const hospitalTypes = [
  { id: 1, title: 'সরকারি\nহাসপাতাল', titleEn: 'Govt\nHospital', icon: Building2 },
  { id: 2, title: 'বেসরকারি\nহাসপাতাল', titleEn: 'Private\nHospital', icon: Building2 },
  { id: 3, title: 'ক্লিনিক &\nডায়াগনস্টিক', titleEn: 'Clinic &\nDiagnostic', icon: Eye },
  { id: 4, title: 'মাতৃসেবা\nকেন্দ্র', titleEn: 'Maternity\nCenter', icon: Baby },
  { id: 5, title: 'চক্ষু\nহাসপাতাল', titleEn: 'Eye\nHospital', icon: Eye },
  { id: 6, title: 'দন্ত\nহাসপাতাল', titleEn: 'Dental\nHospital', icon: Smile },
];

export const doctorTypes = [
  { id: 1, title: 'মেডিসিন', titleEn: 'Medicine', icon: Stethoscope },
  { id: 2, title: 'চোখের\nডাক্তার', titleEn: 'Eye\nDoctor', icon: Eye },
  { id: 3, title: 'দাঁতের\nডাক্তার', titleEn: 'Dental\nDoctor', icon: Smile },
  { id: 4, title: 'হৃদরোগ', titleEn: 'Cardiology', icon: Heart },
  { id: 5, title: 'নিউরো', titleEn: 'Neurology', icon: Brain },
  { id: 6, title: 'শিশু', titleEn: 'Pediatrics', icon: Baby },
  { id: 7, title: 'হাড় ও জোড়া', titleEn: 'Orthopedics', icon: Bone },
  { id: 8, title: 'কান\nনাক গলা', titleEn: 'ENT', icon: Ear },
  { id: 9, title: 'চর্ম ও\nযৌন', titleEn: 'Dermatology', icon: Activity },
  { id: 10, title: 'ডায়াবেটিস', titleEn: 'Diabetes', icon: Thermometer },
];

export const featuredDoctors = [
  {
    id: 1,
    name: 'ডা. মোঃ রফিকুল ইসলাম',
    nameEn: 'Dr. Md. Rafiqul Islam',
    specialty: 'হৃদরোগ বিশেষজ্ঞ',
    specialtyEn: 'Cardiologist',
    hospital: 'ঢাকা মেডিকেল কলেজ',
    hospitalEn: 'Dhaka Medical College',
    rating: '৪.৯',
    reviews: '২৩৪',
    fee: '৮০০৳',
    available: true,
    exp: '১৫ বছর',
    expEn: '15 years',
  },
  {
    id: 2,
    name: 'ডা. সুমাইয়া বেগম',
    nameEn: 'Dr. Sumaiya Begum',
    specialty: 'চক্ষু বিশেষজ্ঞ',
    specialtyEn: 'Ophthalmologist',
    hospital: 'ইসলামী ব্যাংক হাসপাতাল',
    hospitalEn: 'Islami Bank Hospital',
    rating: '৪.৮',
    reviews: '১৮৭',
    fee: '৬০০৳',
    available: true,
    exp: '১২ বছর',
    expEn: '12 years',
  },
  {
    id: 3,
    name: 'ডা. আবুল কাশেম',
    nameEn: 'Dr. Abul Kashem',
    specialty: 'দন্ত বিশেষজ্ঞ',
    specialtyEn: 'Dentist',
    hospital: 'স্কয়ার হাসপাতাল',
    hospitalEn: 'Square Hospital',
    rating: '৪.৭',
    reviews: '৯৮',
    fee: '৫০০৳',
    available: false,
    exp: '৮ বছর',
    expEn: '8 years',
  },
];

export const nearbyHospitals = [
  {
    id: 1,
    name: 'ঢাকা মেডিকেল কলেজ',
    nameEn: 'Dhaka Medical College',
    type: 'সরকারি',
    typeEn: 'Government',
    distance: '১.২ কিমি',
    distanceEn: '1.2 km',
    beds: '২৩০০',
    open: true,
    img: 'https://images.unsplash.com/photo-1723056416893-e38cdbd35685?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=200',
  },
  {
    id: 2,
    name: 'স্কয়ার হাসপাতাল লিমিটেড',
    nameEn: 'Square Hospital Limited',
    type: 'বেসরকারি',
    typeEn: 'Private',
    distance: '৩.৫ কিমি',
    distanceEn: '3.5 km',
    beds: '৫৬০',
    open: true,
    img: 'https://images.unsplash.com/photo-1723056416893-e38cdbd35685?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=200',
  },
];

export const upcomingAppointments = [
  {
    id: 1,
    doctorName: 'ডা. মোঃ রফিকুল ইসলাম',
    doctorNameEn: 'Dr. Md. Rafiqul Islam',
    specialty: 'হৃদরোগ বিশেষজ্ঞ',
    specialtyEn: 'Cardiologist',
    hospital: 'ঢাকা মেডিকেল কলেজ',
    hospitalEn: 'Dhaka Medical College',
    date: '২৫ মে, ২০২৬',
    dateEn: '25 May, 2026',
    time: 'সকাল ১০:৩০',
    timeEn: '10:30 AM',
    status: 'আগামী',
    statusEn: 'Upcoming',
    color: { bg: '#E8F5E9', icon: '#2E7D32' },
  },
  {
    id: 2,
    doctorName: 'ডা. সুমাইয়া বেগম',
    doctorNameEn: 'Dr. Sumaiya Begum',
    specialty: 'চক্ষু বিশেষজ্ঞ',
    specialtyEn: 'Ophthalmologist',
    hospital: 'ইসলামী ব্যাংক হাসপাতাল',
    hospitalEn: 'Islami Bank Hospital',
    date: '২৮ মে, ২০২৬',
    dateEn: '28 May, 2026',
    time: 'বিকাল ৩:০০',
    timeEn: '3:00 PM',
    status: 'আগামী',
    statusEn: 'Upcoming',
    color: { bg: '#E3F2FD', icon: '#1565C0' },
  },
  {
    id: 3,
    doctorName: 'ডা. আবুল কাশেম',
    doctorNameEn: 'Dr. Abul Kashem',
    specialty: 'দন্ত বিশেষজ্ঞ',
    specialtyEn: 'Dentist',
    hospital: 'স্কয়ার হাসপাতাল',
    hospitalEn: 'Square Hospital',
    date: '৩০ মে, ২০২৬',
    dateEn: '30 May, 2026',
    time: 'দুপুর ১২:০০',
    timeEn: '12:00 PM',
    status: 'আগামী',
    statusEn: 'Upcoming',
    color: { bg: '#FFF3E0', icon: '#E65100' },
  },
];

export const notifications = [
  {
    id: 1,
    title: 'অ্যাপয়েন্টমেন্ট রিমাইন্ডার',
    titleEn: 'Appointment Reminder',
    message: 'আগামীকাল সকাল ১০:৩০ এ ডা. রফিকুল ইসলামের সাথে আপনার অ্যাপয়েন্টমেন্ট',
    messageEn: 'Your appointment with Dr. Rafiqul Islam is tomorrow at 10:30 AM',
    time: '২ ঘন্টা আগে',
    timeEn: '2 hours ago',
    unread: true,
    icon: Calendar,
    color: '#2E7D32',
  },
  {
    id: 2,
    title: 'নতুন ল্যাব রিপোর্ট',
    titleEn: 'New Lab Report',
    message: 'আপনার রক্ত পরীক্ষার রিপোর্ট প্রস্তুত',
    messageEn: 'Your blood test report is ready',
    time: '৫ ঘন্টা আগে',
    timeEn: '5 hours ago',
    unread: true,
    icon: FlaskConical,
    color: '#E65100',
  },
  {
    id: 3,
    title: 'প্রেসক্রিপশন আপডেট',
    titleEn: 'Prescription Update',
    message: 'ডা. সুমাইয়া বেগম আপনার প্রেসক্রিপশন আপডেট করেছেন',
    messageEn: 'Dr. Sumaiya Begum has updated your prescription',
    time: '১ দিন আগে',
    timeEn: '1 day ago',
    unread: false,
    icon: Pill,
    color: '#1565C0',
  },
];

export const quickServices = [
  {
    id: 1,
    title: 'অ্যাম্বুলেন্স',
    titleEn: 'Ambulance',
    subtitle: 'জরুরি সেবা',
    subtitleEn: 'Emergency Service',
    icon: Truck,
    bg: 'from-red-500 to-red-600',
    img: 'https://images.unsplash.com/photo-1655084131262-73cbdc46522b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=300',
  },
  {
    id: 2,
    title: 'ব্লাড ব্যাংক',
    titleEn: 'Blood Bank',
    subtitle: 'রক্তের অনুরোধ',
    subtitleEn: 'Blood Request',
    icon: Droplets,
    bg: 'from-rose-500 to-pink-600',
    img: 'https://images.unsplash.com/photo-1605714007165-c15eac9c647b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=300',
  },
  {
    id: 3,
    title: 'ফার্মেসি',
    titleEn: 'Pharmacy',
    subtitle: 'ওষুধ অর্ডার',
    subtitleEn: 'Medicine Order',
    icon: Pill,
    bg: 'from-teal-500 to-green-600',
    img: 'https://images.unsplash.com/photo-1765031092161-a9ebe556117e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=300',
  },
];

export const quickStats = [
  { id: 1, labelBn: 'ডাক্তার', labelEn: 'Doctors', value: '৫০০+' },
  { id: 2, labelBn: 'হাসপাতাল', labelEn: 'Hospitals', value: '১২০+' },
  { id: 3, labelBn: 'ফার্মেসি', labelEn: 'Pharmacy', value: '৮০+' },
  { id: 4, labelBn: 'ল্যাব', labelEn: 'Labs', value: '৬০+' },
];

export const profileMenuItems = [
  { id: 1, iconName: 'Calendar', labelBn: 'আমার অ্যাপয়েন্টমেন্ট', labelEn: 'My Appointments', count: '৩', color: '#2E7D32' },
  { id: 2, iconName: 'Clock', labelBn: 'চিকিৎসার ইতিহাস', labelEn: 'Medical History', count: '১২', color: '#1565C0' },
  { id: 3, iconName: 'Pill', labelBn: 'প্রেসক্রিপশন', labelEn: 'Prescription', count: '৫', color: '#6A1B9A' },
  { id: 4, iconName: 'FlaskConical', labelBn: 'ল্যাব রিপোর্ট', labelEn: 'Lab Reports', count: '৮', color: '#E65100' },
  { id: 5, iconName: 'Bell', labelBn: 'বিজ্ঞপ্তি সেটিংস', labelEn: 'Notification Settings', count: null, color: '#F57F17' },
  { id: 6, iconName: 'ShieldCheck', labelBn: 'গোপনীয়তা ও নিরাপত্তা', labelEn: 'Privacy & Security', count: null, color: '#00695C' },
];
